/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Bsp.h"

#define REL_VAL (65536 - 30518) /* Reload value for extended timeout window */
#define WAIT_TIME 1000          /* Number of milliseconds to wait           */

IFX_ALIGN(4)
IfxCpu_syncEvent cpuSyncEvent = 0;

void (*appA)(void) = (void (*)(void))0xA0020000;

void jumpToApplicationA(void)
{
    IfxCpu_disableInterrupts();
    MODULE_SRC.SCU.SCUERU[0].B.SRE = 0;
    appA();
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */

    /*IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());*/ /* Set CPU0 WD timer active     */

    uint16 password = IfxScuWdt_getCpuWatchdogPassword();
    IfxScuWdt_disableSafetyWatchdog(password);            /* Safety WD remains disabled   */
    IfxScuWdt_changeCpuWatchdogReload(password, REL_VAL); /* Set CPU0WD timer to ~3 sec */
    IfxScuWdt_serviceCpuWatchdog(password);               /* Service the CPU0WDT          */

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    MODULE_P00.IOCR4.B.PC5 = 0x10; // LED 1
    MODULE_P00.IOCR4.B.PC6 = 0x10; // LED 2
    P00_OUT.B.P5 = 0;              // Turn On LED 1
    P00_OUT.B.P6 = 0;              // Turn On LED 2


    
    uint16 safetyPassword = IfxScuWdt_getSafetyWatchdogPassword();
    IfxScuWdt_clearSafetyEndinit(safetyPassword);
    MODULE_SCU.RSTCON.B.SMU = 0x01;
    IfxScuWdt_setSafetyEndinit(safetyPassword);
    

    Ifx_TickTime ticksFor1s = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);
    sint64 targetTime = IfxStm_now() + ticksFor1s;

    while (1)
    {
        if(IfxStm_now() >= targetTime)
        {
            targetTime = IfxStm_now() + ticksFor1s;
            P00_OUT.B.P5 = !P00_OUT.B.P5; // Toggle LED 1
            P00_OUT.B.P6 = !P00_OUT.B.P6; // Toggle LED 2
            IfxScuWdt_serviceCpuWatchdog(password); // Service the CPU0WDT
        }

        if(P00_IN.B.P7 == 0)
        {
            jumpToApplicationA();
        }
    }
}
